# Generated by Django 4.2.10 on 2024-02-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_thresholds', models.CharField(max_length=255)),
                ('data_retention_policy', models.CharField(max_length=255)),
                ('performance_baselines', models.CharField(max_length=255)),
                ('feedback_channels', models.CharField(max_length=255)),
            ],
        ),
    ]
